name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'  

    - name: Change directory to springboot-crud
      run: cd springboot-crud

    - name: Build with Maven
      run: mvn -B package --file springboot-crud/pom.xml

    - name: Run tests
      run: mvn test --file springboot-crud/pom.xml

    - name: Run integration tests
      run: mvn verify -P integration --file springboot-crud/pom.xml
